---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    exclude:
      - gh-pages
      - github-pages

clone:
  depth: 2

steps:
  - name: install
    image: node:16
    commands:
      - yarn

  - name: prebuild
    image: node:16
    commands:
      - yarn lint
      - yarn t

  - name: build
    image: node:16
    commands:
      - yarn build

  - name: publish-site
    failure: ignore
    image: plugins/gh-pages
    settings:
      pages_directory: public/
      username:
        from_secret: github_token
      password: x-oauth-basic
    when:
      branch:
        - dev
      event:
        exclude:
          - pull-request
